//! Pure rendering of the `.env.portool` file contents (spec §7.1).

use crate::manifest::{env_var_name, Manifest};
use std::fmt::Write as _;

/// Renders the `.env.portool` contents for a worktree.
///
/// The header is always the two-line comment block naming the block,
/// project, and worktree path. When `manifest` is `Some`, one
/// `<KEY>_PORT=<port>` line is emitted per declared port, in the manifest's
/// (offset-ascending) order. When `manifest` is `None`, a single
/// `PORT=<block_start>` line is emitted instead.
pub fn render(
    project_name: &str,
    worktree_path: &str,
    block: (u16, u16),
    manifest: Option<&Manifest>,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# generated by portool \u{2014} DO NOT EDIT");
    let _ = writeln!(
        out,
        "# block: {}-{}  project: {}  worktree: {}",
        block.0, block.1, project_name, worktree_path
    );

    match manifest {
        Some(m) => {
            for (key, offset) in &m.ports {
                let port = block.0 + offset;
                let _ = writeln!(out, "{}={}", env_var_name(key), port);
            }
        }
        None => {
            let _ = writeln!(out, "PORT={}", block.0);
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    #[test]
    fn renders_manifest_exact_bytes() {
        let manifest = Manifest::parse("[ports]\nweb = 0\napi = 1\nhmr = 2\ndb = 3\n").unwrap();
        let rendered = render(
            "esimdb",
            "/home/takuto/dev/esimdb",
            (3000, 3004),
            Some(&manifest),
        );

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  project: esimdb  worktree: /home/takuto/dev/esimdb\n\
WEB_PORT=3000\n\
API_PORT=3001\n\
HMR_PORT=3002\n\
DB_PORT=3003\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn renders_default_port_line_when_no_manifest() {
        let rendered = render("esimdb", "/home/takuto/dev/esimdb", (3000, 3004), None);

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  project: esimdb  worktree: /home/takuto/dev/esimdb\n\
PORT=3000\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn ends_with_trailing_newline() {
        let rendered = render("p", "/w", (3000, 3004), None);
        assert!(rendered.ends_with('\n'));
    }
}
