//! Pure rendering of the `.env.portool` file contents (spec §7.1).

use crate::manifest::{env_var_name, Manifest};
use std::fmt::Write as _;

/// Renders the `.env.portool` contents for a worktree.
///
/// The header is always the two-line comment block naming the block,
/// project, and worktree path, followed by the two stable identity lines
/// (`PORTOOL_PROJECT_ID=` / `PORTOOL_WORKTREE_ID=`), which are emitted
/// whether or not a manifest exists. When `manifest` is `Some`, one
/// `<KEY>_PORT=<port>` line is emitted per declared port, in the manifest's
/// (offset-ascending) order. When `manifest` is `None`, a single
/// `PORT=<block_start>` line is emitted instead.
pub fn render(
    project_name: &str,
    worktree_path: &str,
    block: (u16, u16),
    manifest: Option<&Manifest>,
    project_id: &str,
    worktree_id: &str,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# generated by portool \u{2014} DO NOT EDIT");
    let _ = writeln!(
        out,
        "# block: {}-{}  project: {}  worktree: {}",
        block.0, block.1, project_name, worktree_path
    );
    let _ = writeln!(out, "PORTOOL_PROJECT_ID={project_id}");
    let _ = writeln!(out, "PORTOOL_WORKTREE_ID={worktree_id}");

    match manifest {
        Some(m) => {
            for (key, offset) in &m.ports {
                let port = block.0 + offset;
                let _ = writeln!(out, "{}={}", env_var_name(key), port);
            }
        }
        None => {
            let _ = writeln!(out, "PORT={}", block.0);
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    const PROJECT_ID: &str = "abe4c983b7295f37";
    const WORKTREE_ID: &str = "740da24128c5e2f7";

    #[test]
    fn renders_manifest_exact_bytes() {
        let manifest = Manifest::parse("[ports]\nweb = 0\napi = 1\nhmr = 2\ndb = 3\n").unwrap();
        let rendered = render(
            "myapp",
            "/home/user/dev/myapp",
            (3000, 3004),
            Some(&manifest),
            PROJECT_ID,
            WORKTREE_ID,
        );

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  project: myapp  worktree: /home/user/dev/myapp\n\
PORTOOL_PROJECT_ID=abe4c983b7295f37\n\
PORTOOL_WORKTREE_ID=740da24128c5e2f7\n\
WEB_PORT=3000\n\
API_PORT=3001\n\
HMR_PORT=3002\n\
DB_PORT=3003\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn renders_default_port_line_when_no_manifest() {
        let rendered = render(
            "myapp",
            "/home/user/dev/myapp",
            (3000, 3004),
            None,
            PROJECT_ID,
            WORKTREE_ID,
        );

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  project: myapp  worktree: /home/user/dev/myapp\n\
PORTOOL_PROJECT_ID=abe4c983b7295f37\n\
PORTOOL_WORKTREE_ID=740da24128c5e2f7\n\
PORT=3000\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn id_lines_precede_port_variables() {
        let manifest = Manifest::parse("[ports]\nweb = 0\n").unwrap();
        let rendered = render(
            "p",
            "/w",
            (3000, 3004),
            Some(&manifest),
            PROJECT_ID,
            WORKTREE_ID,
        );

        let project_id_pos = rendered.find("PORTOOL_PROJECT_ID=").unwrap();
        let worktree_id_pos = rendered.find("PORTOOL_WORKTREE_ID=").unwrap();
        let port_pos = rendered.find("WEB_PORT=").unwrap();
        assert!(project_id_pos < worktree_id_pos);
        assert!(worktree_id_pos < port_pos);
    }

    #[test]
    fn ends_with_trailing_newline() {
        let rendered = render("p", "/w", (3000, 3004), None, PROJECT_ID, WORKTREE_ID);
        assert!(rendered.ends_with('\n'));
    }
}
