//! Rendering (and header parsing) of the `.env.portool` file contents
//! (spec §7.1).

use crate::manifest::{env_var_name, Manifest};
use std::fmt::Write as _;
use std::path::Path;

/// Renders the `.env.portool` contents for a worktree.
///
/// The header is always the two-line comment block naming the block, its
/// ledger generation, project, and worktree path, followed by the two
/// stable identity lines (`PORTOOL_PROJECT_ID=` / `PORTOOL_WORKTREE_ID=`),
/// which are emitted whether or not a manifest exists. When `manifest` is
/// `Some`, one `<KEY>_PORT=<port>` line is emitted per declared port, in
/// the manifest's (offset-ascending) order. When `manifest` is `None`, a
/// single `PORT=<block_start>` line is emitted instead.
#[allow(clippy::too_many_arguments)]
pub fn render(
    project_name: &str,
    worktree_path: &str,
    block: (u16, u16),
    generation: u64,
    sequence: u64,
    manifest: Option<&Manifest>,
    project_id: &str,
    worktree_id: &str,
) -> crate::error::Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# generated by portool \u{2014} DO NOT EDIT");
    // The project name and worktree path are interpolated into a comment
    // line; a newline or other control character in a (possibly
    // agent-created) worktree path must not be able to escape the comment
    // and inject an executable line into a file the README tells users to
    // `source` (batch D #13). Control characters are replaced with spaces so
    // the header is always a single, inert comment line. `sequence` mirrors
    // the ledger's monotonic counter for stale-backup detection (P0-2).
    let _ = writeln!(
        out,
        "# block: {}-{}  generation: {generation}  sequence: {sequence}  project: {}  worktree: {}",
        block.0,
        block.1,
        sanitize_comment(project_name),
        sanitize_comment(worktree_path)
    );
    for (name, value) in variables(block, manifest, project_id, worktree_id)? {
        let _ = writeln!(out, "{name}={value}");
    }

    Ok(out)
}

/// The portool-managed variables for a worktree, in `.env.portool` order:
/// the two identity lines, then one `<KEY>_PORT` per manifest port (or a
/// single `PORT` when there is no manifest).
pub fn variables(
    block: (u16, u16),
    manifest: Option<&Manifest>,
    project_id: &str,
    worktree_id: &str,
) -> crate::error::Result<Vec<(String, String)>> {
    let mut vars = Vec::new();
    vars.push(("PORTOOL_PROJECT_ID".to_string(), project_id.to_string()));
    vars.push(("PORTOOL_WORKTREE_ID".to_string(), worktree_id.to_string()));

    match manifest {
        Some(m) => {
            for (key, offset) in &m.ports {
                // checked_add + in-block validation (external review P1-6):
                // with a correctly sized block neither can trigger, but a
                // mismatch must be a loud error, never a silently wrapped or
                // out-of-block port.
                let port = block
                    .0
                    .checked_add(*offset)
                    .filter(|p| *p <= block.1)
                    .ok_or_else(|| {
                        crate::error::Error::General(format!(
                            "manifest offset {offset} for '{key}' maps outside the \
                             allocated block {}-{}; run 'portool sync' to resize",
                            block.0, block.1
                        ))
                    })?;
                vars.push((env_var_name(key), port.to_string()));
            }
        }
        None => {
            vars.push(("PORT".to_string(), block.0.to_string()));
        }
    }

    Ok(vars)
}

/// Replaces control characters (including newlines, carriage returns, and
/// tabs) with spaces so an interpolated value can never break out of the
/// single-line comment it sits in.
fn sanitize_comment(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect()
}

/// Extracts the block from a worktree's `.env.portool` header line
/// (`# block: START-END  ...`), or `None` if the file or line is absent or
/// unparseable. Used by `doctor` to rebuild lost ledger entries and by the
/// sync slow path to resolve an interrupted two-phase move (roll forward
/// when the env already carries the pending block, roll back otherwise).
pub fn read_block_from_env(worktree: &Path) -> Option<(u16, u16)> {
    let contents = std::fs::read_to_string(worktree.join(".env.portool")).ok()?;
    for line in contents.lines() {
        if let Some(rest) = line.strip_prefix("# block: ") {
            let token = rest.split_whitespace().next()?;
            let (start, end) = token.split_once('-')?;
            return Some((start.parse().ok()?, end.parse().ok()?));
        }
    }
    None
}

/// The ledger `sequence` recorded in a worktree's `.env.portool` header, or
/// `None` when the file/line is absent or the field is missing/unparseable
/// (e.g. a pre-v0.10 env). Used to detect a restore-from-stale-backup: an env
/// recording a higher sequence than the ledger proves the ledger was rolled
/// back (external review v0.10 P0-2).
pub fn read_sequence_from_env(worktree: &Path) -> Option<u64> {
    let contents = std::fs::read_to_string(worktree.join(".env.portool")).ok()?;
    for line in contents.lines() {
        let Some(rest) = line.strip_prefix("# block: ") else {
            continue;
        };
        let mut it = rest.split_whitespace();
        while let Some(tok) = it.next() {
            if tok == "sequence:" {
                return it.next()?.parse().ok();
            }
        }
    }
    None
}

/// Returns `content` with the `sequence: N` field removed from its `# block:`
/// header line, so the sync fast path can byte-compare the rest of the file
/// without the ledger-global sequence (which changes on every save, including
/// other projects') forcing a needless rewrite. Only the header comment is
/// normalized; every variable line is untouched.
pub fn strip_sequence(content: &str) -> String {
    let mut result = content
        .lines()
        .map(|line| {
            if line.starts_with("# block: ") {
                strip_sequence_field(line)
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    if content.ends_with('\n') {
        result.push('\n');
    }
    result
}

/// Drops the `sequence: N` token pair from the *metadata* region of a single
/// `# block:` header line (everything up to the free-text `project:` field),
/// re-joining the remaining tokens with single spaces. Stopping at `project:`
/// keeps a worktree path that happens to contain a `sequence:` token (paths
/// may hold spaces and colons) from being mangled. Both sides of the
/// fast-path comparison pass through this identically, so the exact spacing
/// does not matter -- only that the real sequence value is gone from both.
fn strip_sequence_field(line: &str) -> String {
    let tokens: Vec<&str> = line.split_whitespace().collect();
    let mut out = Vec::new();
    let mut i = 0;
    let mut in_metadata = true;
    while i < tokens.len() {
        if tokens[i] == "project:" {
            in_metadata = false;
        }
        if in_metadata && tokens[i] == "sequence:" {
            i += 2; // skip "sequence:" and its value
            continue;
        }
        out.push(tokens[i]);
        i += 1;
    }
    out.join(" ")
}

/// The three distinct identity states a worktree's `.env.portool` can be in
/// (external review v0.10 P0-5). A half-written file with exactly one ID line
/// must never be conflated with a legitimately ID-less old file: the former is
/// corruption, the latter is a pre-identity file that `doctor` imports by
/// design.
#[derive(Debug, PartialEq, Eq)]
pub enum EnvIdentity {
    /// Neither ID line is present (file missing/unreadable, or written before
    /// identity lines existed).
    Absent,
    /// Both ID lines are present.
    Complete(String, String),
    /// Exactly one ID line is present -> corruption / manual repair required.
    Partial,
}

/// Three-valued identity read (external review v0.10 P0-5).
pub fn read_identity_from_env(worktree: &Path) -> EnvIdentity {
    let contents = match std::fs::read_to_string(worktree.join(".env.portool")) {
        Ok(contents) => contents,
        Err(_) => return EnvIdentity::Absent,
    };
    let mut project = None;
    let mut wt = None;
    for line in contents.lines() {
        if let Some(v) = line.strip_prefix("PORTOOL_PROJECT_ID=") {
            project = Some(v.trim().to_string());
        } else if let Some(v) = line.strip_prefix("PORTOOL_WORKTREE_ID=") {
            wt = Some(v.trim().to_string());
        }
    }
    match (project, wt) {
        (Some(p), Some(w)) => EnvIdentity::Complete(p, w),
        (None, None) => EnvIdentity::Absent,
        _ => EnvIdentity::Partial,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    const PROJECT_ID: &str = "abe4c983b7295f370a207b1614878153";
    const WORKTREE_ID: &str = "740da24128c5e2f7abf4fa15ab4253f3";

    #[test]
    fn variables_rejects_an_offset_outside_the_block() {
        // Defense in depth (P1-6): a ledger/manifest mismatch must never
        // silently emit a port outside the allocated block.
        let manifest = Manifest::parse("[ports]\nweb = 0\ndb = 9\n").unwrap();
        let err = variables((3000, 3004), Some(&manifest), PROJECT_ID, WORKTREE_ID).unwrap_err();
        assert!(err.to_string().contains("outside"));
    }

    #[test]
    fn renders_manifest_exact_bytes() {
        let manifest = Manifest::parse("[ports]\nweb = 0\napi = 1\nhmr = 2\ndb = 3\n").unwrap();
        let rendered = render(
            "myapp",
            "/home/user/dev/myapp",
            (3000, 3004),
            1,
            5,
            Some(&manifest),
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  generation: 1  sequence: 5  project: myapp  worktree: /home/user/dev/myapp\n\
PORTOOL_PROJECT_ID=abe4c983b7295f370a207b1614878153\n\
PORTOOL_WORKTREE_ID=740da24128c5e2f7abf4fa15ab4253f3\n\
WEB_PORT=3000\n\
API_PORT=3001\n\
HMR_PORT=3002\n\
DB_PORT=3003\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn renders_default_port_line_when_no_manifest() {
        let rendered = render(
            "myapp",
            "/home/user/dev/myapp",
            (3000, 3004),
            2,
            9,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();

        let expected = "# generated by portool \u{2014} DO NOT EDIT\n\
# block: 3000-3004  generation: 2  sequence: 9  project: myapp  worktree: /home/user/dev/myapp\n\
PORTOOL_PROJECT_ID=abe4c983b7295f370a207b1614878153\n\
PORTOOL_WORKTREE_ID=740da24128c5e2f7abf4fa15ab4253f3\n\
PORT=3000\n";

        assert_eq!(rendered, expected);
    }

    #[test]
    fn id_lines_precede_port_variables() {
        let manifest = Manifest::parse("[ports]\nweb = 0\n").unwrap();
        let rendered = render(
            "p",
            "/w",
            (3000, 3004),
            1,
            3,
            Some(&manifest),
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();

        let project_id_pos = rendered.find("PORTOOL_PROJECT_ID=").unwrap();
        let worktree_id_pos = rendered.find("PORTOOL_WORKTREE_ID=").unwrap();
        let port_pos = rendered.find("WEB_PORT=").unwrap();
        assert!(project_id_pos < worktree_id_pos);
        assert!(worktree_id_pos < port_pos);
    }

    #[test]
    fn variables_match_render_body_with_manifest() {
        let manifest = Manifest::parse("[ports]\nweb = 0\napi = 1\nhmr = 2\ndb = 3\n").unwrap();
        let block = (3000, 3004);

        let vars = variables(block, Some(&manifest), PROJECT_ID, WORKTREE_ID).unwrap();
        assert_eq!(
            vars,
            vec![
                ("PORTOOL_PROJECT_ID".to_string(), PROJECT_ID.to_string()),
                ("PORTOOL_WORKTREE_ID".to_string(), WORKTREE_ID.to_string()),
                ("WEB_PORT".to_string(), "3000".to_string()),
                ("API_PORT".to_string(), "3001".to_string()),
                ("HMR_PORT".to_string(), "3002".to_string()),
                ("DB_PORT".to_string(), "3003".to_string()),
            ]
        );

        // render() must be exactly the two comment lines plus these
        // variables, so the two can never drift apart.
        let rendered = render(
            "myapp",
            "/home/user/dev/myapp",
            block,
            1,
            3,
            Some(&manifest),
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        let body: Vec<(String, String)> = rendered
            .lines()
            .filter(|line| !line.starts_with('#'))
            .map(|line| {
                let (name, value) = line.split_once('=').unwrap();
                (name.to_string(), value.to_string())
            })
            .collect();
        assert_eq!(body, vars);
    }

    #[test]
    fn variables_use_single_port_line_when_no_manifest() {
        let vars = variables((3000, 3004), None, PROJECT_ID, WORKTREE_ID).unwrap();
        assert_eq!(
            vars,
            vec![
                ("PORTOOL_PROJECT_ID".to_string(), PROJECT_ID.to_string()),
                ("PORTOOL_WORKTREE_ID".to_string(), WORKTREE_ID.to_string()),
                ("PORT".to_string(), "3000".to_string()),
            ]
        );
    }

    #[test]
    fn ends_with_trailing_newline() {
        let rendered =
            render("p", "/w", (3000, 3004), 1, 3, None, PROJECT_ID, WORKTREE_ID).unwrap();
        assert!(rendered.ends_with('\n'));
    }

    #[test]
    fn read_block_from_env_round_trips_with_render() {
        let tmp = tempfile::TempDir::new().unwrap();
        let rendered =
            render("p", "/w", (3005, 3009), 4, 3, None, PROJECT_ID, WORKTREE_ID).unwrap();
        std::fs::write(tmp.path().join(".env.portool"), rendered).unwrap();

        assert_eq!(read_block_from_env(tmp.path()), Some((3005, 3009)));
    }

    #[test]
    fn read_block_from_env_missing_file_is_none() {
        let tmp = tempfile::TempDir::new().unwrap();
        assert_eq!(read_block_from_env(tmp.path()), None);
    }

    #[test]
    fn read_sequence_from_env_round_trips() {
        let tmp = tempfile::TempDir::new().unwrap();
        let rendered = render(
            "p",
            "/w",
            (3005, 3009),
            4,
            42,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        std::fs::write(tmp.path().join(".env.portool"), rendered).unwrap();
        assert_eq!(read_sequence_from_env(tmp.path()), Some(42));
    }

    #[test]
    fn read_sequence_from_env_absent_when_no_sequence_field() {
        let tmp = tempfile::TempDir::new().unwrap();
        // A pre-v0.10 header without a sequence field.
        std::fs::write(
            tmp.path().join(".env.portool"),
            "# generated by portool\n# block: 3000-3004  generation: 1  project: p  worktree: /w\nPORT=3000\n",
        )
        .unwrap();
        assert_eq!(read_sequence_from_env(tmp.path()), None);
    }

    #[test]
    fn strip_sequence_makes_headers_with_differing_sequence_compare_equal() {
        let a = render("p", "/w", (3000, 3004), 1, 1, None, PROJECT_ID, WORKTREE_ID).unwrap();
        let b = render(
            "p",
            "/w",
            (3000, 3004),
            1,
            999,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        assert_ne!(a, b, "raw renders differ only in sequence");
        assert_eq!(
            strip_sequence(&a),
            strip_sequence(&b),
            "stripping the sequence field must make them equal"
        );
    }

    #[test]
    fn strip_sequence_leaves_variable_lines_untouched() {
        let rendered =
            render("p", "/w", (3000, 3004), 1, 5, None, PROJECT_ID, WORKTREE_ID).unwrap();
        let stripped = strip_sequence(&rendered);
        assert!(stripped.contains("PORT=3000"));
        assert!(!stripped.contains("sequence:"));
    }

    #[test]
    fn strip_sequence_does_not_mangle_a_worktree_path_containing_sequence() {
        // A worktree path holding a `sequence:` token (paths may contain
        // spaces and colons) must not lose part of its path -- only the real
        // metadata `sequence:` field, before `project:`, is stripped.
        let a = render(
            "p",
            "/home/u/sequence: 900/repo",
            (3000, 3004),
            1,
            1,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        let b = render(
            "p",
            "/home/u/sequence: 900/repo",
            (3000, 3004),
            1,
            999,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        assert_eq!(strip_sequence(&a), strip_sequence(&b));
        assert!(strip_sequence(&a).contains("sequence: 900/repo"));
    }

    #[test]
    fn read_identity_from_env_parses_both_ids() {
        let tmp = tempfile::TempDir::new().unwrap();
        let rendered =
            render("p", "/w", (3005, 3009), 4, 3, None, PROJECT_ID, WORKTREE_ID).unwrap();
        std::fs::write(tmp.path().join(".env.portool"), rendered).unwrap();

        assert_eq!(
            read_identity_from_env(tmp.path()),
            EnvIdentity::Complete(PROJECT_ID.to_string(), WORKTREE_ID.to_string())
        );
    }

    #[test]
    fn read_identity_from_env_missing_file_is_absent() {
        let tmp = tempfile::TempDir::new().unwrap();
        assert_eq!(read_identity_from_env(tmp.path()), EnvIdentity::Absent);
    }

    #[test]
    fn read_identity_from_env_three_valued() {
        let tmp = tempfile::TempDir::new().unwrap();
        let env = tmp.path().join(".env.portool");
        // Only project -> Partial.
        std::fs::write(&env, "PORTOOL_PROJECT_ID=aa\nPORT=3000\n").unwrap();
        assert_eq!(read_identity_from_env(tmp.path()), EnvIdentity::Partial);
        // Only worktree -> Partial.
        std::fs::write(&env, "PORTOOL_WORKTREE_ID=bb\nPORT=3000\n").unwrap();
        assert_eq!(read_identity_from_env(tmp.path()), EnvIdentity::Partial);
        // Neither -> Absent (a pre-identity file).
        std::fs::write(&env, "PORT=3000\n").unwrap();
        assert_eq!(read_identity_from_env(tmp.path()), EnvIdentity::Absent);
        // Both -> Complete.
        std::fs::write(&env, "PORTOOL_PROJECT_ID=aa\nPORTOOL_WORKTREE_ID=bb\n").unwrap();
        assert_eq!(
            read_identity_from_env(tmp.path()),
            EnvIdentity::Complete("aa".to_string(), "bb".to_string())
        );
    }

    #[test]
    fn a_newline_in_the_worktree_path_cannot_escape_the_comment() {
        // A hostile/agent-created worktree path containing a newline + an
        // executable-looking line must not inject a second line the shell
        // would run when the file is `source`d (batch D #13).
        let rendered = render(
            "p",
            "/tmp/wt\necho PWNED > /tmp/pwned",
            (3000, 3004),
            1,
            3,
            None,
            PROJECT_ID,
            WORKTREE_ID,
        )
        .unwrap();
        // Every non-`#` line is a `KEY=value` portool variable; no injected
        // `echo ...` line survives.
        for line in rendered.lines().filter(|l| !l.starts_with('#')) {
            assert!(
                line.contains('=') && !line.contains("echo"),
                "unexpected non-variable line leaked in: {line:?}"
            );
        }
        // The comment header stayed a single line.
        let comment_lines = rendered.lines().filter(|l| l.starts_with('#')).count();
        assert_eq!(comment_lines, 2);
    }
}
