//! Effective hooks-location discovery: where git will actually look for
//! `post-checkout` in this repository, honoring `core.hooksPath` (set by
//! hook managers like Husky) instead of assuming `<common_dir>/hooks`.

use crate::gitctx::{self, GitCtx};
use std::ffi::OsStr;
use std::path::{Component, Path, PathBuf};

/// The substring that marks a legacy appended portool line (the pre-managed-
/// block forms `init` used to emit) as portool's own; only
/// [`contains_portool_invocation`] still keys off it directly.
pub const HOOK_MARKER: &str = "portool sync";

/// The comment on the *second* line of portool's owned standalone hook
/// script. Its presence there -- regardless of anything else in the file --
/// identifies the file as portool's own, covering every shape portool has
/// ever emitted (old and new); `init` rewrites such a file wholesale when
/// its content goes stale (e.g. a moved binary path).
pub const HOOK_OWNED_COMMENT: &str = "# installed by portool";

/// Marks the start of the managed block `init` appends to a foreign hook.
pub const HOOK_BLOCK_BEGIN: &str = "# >>> portool >>>";

/// Marks the end of the managed block `init` appends to a foreign hook.
pub const HOOK_BLOCK_END: &str = "# <<< portool <<<";

/// True when `content` carries any portool hook form: an owned standalone
/// script, a managed block, or a legacy appended line. Intentionally a
/// loose substring heuristic -- used only for warnings/hints (e.g. `sync`'s
/// missing-hook nag), never for install/deinit decisions, which use the
/// line-exact checks in `crate::cmd::init`.
pub fn contains_portool_invocation(content: &str) -> bool {
    content.contains(HOOK_OWNED_COMMENT)
        || content.contains(HOOK_BLOCK_BEGIN)
        || content.contains(HOOK_MARKER)
}

/// Where portool's `post-checkout` invocation belongs for this repository.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HooksLocation {
    /// No `core.hooksPath`: git's default `<common_dir>/hooks`.
    GitDefault { hooks_dir: PathBuf },
    /// `core.hooksPath` points at Husky's generated runtime dir
    /// (`.husky/_`). That dir is gitignored and regenerated by Husky, so
    /// portool's hook belongs in the user-managed `.husky/post-checkout`
    /// one level up, which Husky's own bootstrap dispatches to (keeping
    /// `HUSKY=0`, `~/.config/husky/init.sh`, PATH setup, `sh -e`, and
    /// exit-code propagation intact).
    Husky { hook_file: PathBuf },
    /// Some other `core.hooksPath` whose directory exists.
    Custom { hooks_dir: PathBuf },
    /// `core.hooksPath` is set but doesn't point at an existing directory
    /// -- missing, or an existing non-directory (likely a generated dir
    /// portool doesn't recognize); installing anywhere would either be
    /// discarded or never run, so nothing is safe to touch.
    Missing {
        configured: String,
        resolved: PathBuf,
    },
    /// `core.hooksPath` resolves (after canonicalization) to a directory
    /// outside this repository -- whatever scope set it, and however it
    /// escaped (absolute path, relative `../`, or a symlink). Auto-installing
    /// there could run portool's hook on every repo that shares -- or
    /// symlinks to -- that directory, so it is refused; `init` prints the
    /// manual line instead.
    SharedScope {
        configured: String,
        resolved: PathBuf,
        scope: String,
    },
}

impl HooksLocation {
    /// Resolves the effective hooks location for `ctx` by reading
    /// `core.hooksPath` (with `~` expanded) from the worktree.
    ///
    /// Whatever scope set `core.hooksPath` (`local`, `worktree`, `global`,
    /// `system`, or even `command`-line `-c`), and however the configured
    /// value resolves -- an absolute path, a relative `../` escape, or a
    /// symlink into another directory -- a resolved location outside this
    /// repository (`worktree_root` / `common_dir`) is reported as
    /// [`HooksLocation::SharedScope`] so `init` refuses to auto-install
    /// there. This check runs *before* any other classification, so a
    /// shared dir cannot slip through by looking like Husky's `.husky/_`
    /// (external review P1 #3, hardened further to close relative/symlink
    /// escapes and non-global scopes).
    pub fn resolve(ctx: &GitCtx) -> HooksLocation {
        let configured = gitctx::config_path_value(&ctx.worktree_root, "core.hooksPath");

        if let Some(value) = configured.as_deref().filter(|v| !v.trim().is_empty()) {
            let raw = PathBuf::from(value);
            let resolved = if raw.is_absolute() {
                raw
            } else {
                ctx.worktree_root.join(raw)
            };
            // canonicalize resolves symlinks; when it cannot be canonicalized
            // (typically: it does not exist), this falls back to a lexical
            // `..` resolution so `../x` cannot dodge the check by not
            // existing yet.
            let canonical = resolved
                .canonicalize()
                .unwrap_or_else(|_| lexical_normalize(&resolved));

            if !is_inside_repo(&canonical, &ctx.worktree_root, &ctx.common_dir) {
                let scope = gitctx::config_scope(&ctx.worktree_root, "core.hooksPath");
                return HooksLocation::SharedScope {
                    configured: value.to_string(),
                    resolved: canonical,
                    scope: scope.unwrap_or_else(|| "unknown".to_string()),
                };
            }
        }

        classify(configured, &ctx.worktree_root, &ctx.common_dir)
    }

    /// The file portool installs the named hook into (and `sync` checks),
    /// or `None` when no location is safe to auto-install into. `name` is a
    /// git hook name such as `"post-checkout"` or `"post-merge"`.
    pub fn hook_file(&self, name: &str) -> Option<PathBuf> {
        match self {
            HooksLocation::GitDefault { hooks_dir } | HooksLocation::Custom { hooks_dir } => {
                Some(hooks_dir.join(name))
            }
            // The stored path is `<.husky>/post-checkout`; sibling hooks
            // live next to it (`<.husky>/post-merge`, ...).
            HooksLocation::Husky { hook_file } => hook_file.parent().map(|dir| dir.join(name)),
            HooksLocation::Missing { .. } | HooksLocation::SharedScope { .. } => None,
        }
    }
}

/// Pure classification of a raw `core.hooksPath` value (spec: relative
/// paths resolve against the worktree root, per githooks(5) hooks running
/// at the top level of the working tree; an unset or empty value means
/// git's default directory).
fn classify(configured: Option<String>, worktree_root: &Path, common_dir: &Path) -> HooksLocation {
    let configured = match configured {
        Some(value) if !value.trim().is_empty() => value,
        _ => {
            return HooksLocation::GitDefault {
                hooks_dir: common_dir.join("hooks"),
            }
        }
    };

    let raw = PathBuf::from(&configured);
    let resolved = if raw.is_absolute() {
        raw
    } else {
        worktree_root.join(raw)
    };

    if is_husky_runtime_dir(&resolved) {
        // `.husky/_` -> the user-managed `.husky/post-checkout`. Husky is
        // recognized even before `_` is generated: the config pointing at
        // it is proof enough, and `.husky/` itself is a tracked dir.
        let husky_dir = resolved.parent().unwrap_or(&resolved).to_path_buf();
        return HooksLocation::Husky {
            hook_file: husky_dir.join("post-checkout"),
        };
    }

    if resolved.is_dir() {
        HooksLocation::Custom {
            hooks_dir: resolved,
        }
    } else {
        HooksLocation::Missing {
            configured,
            resolved,
        }
    }
}

/// True when `resolved` is inside this repository: under the worktree root
/// or under the git common dir (both already canonical from `GitCtx`).
fn is_inside_repo(resolved: &Path, worktree_root: &Path, common_dir: &Path) -> bool {
    resolved.starts_with(worktree_root) || resolved.starts_with(common_dir)
}

/// Textual `.`/`..` resolution for paths that cannot be canonicalized
/// (target does not exist). Does not touch the filesystem.
fn lexical_normalize(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for c in path.components() {
        match c {
            Component::ParentDir => {
                out.pop();
            }
            Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }
    out
}

/// True for any path whose final two components are `.husky/_` (Husky's
/// generated runtime dir), tolerating a trailing slash.
fn is_husky_runtime_dir(path: &Path) -> bool {
    let mut components = path.components().rev().filter_map(|c| match c {
        Component::Normal(name) => Some(name),
        _ => None,
    });
    components.next() == Some(OsStr::new("_")) && components.next() == Some(OsStr::new(".husky"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> PathBuf {
        PathBuf::from("/work/repo")
    }

    fn common() -> PathBuf {
        PathBuf::from("/work/repo/.git")
    }

    #[test]
    fn unset_and_empty_mean_git_default() {
        for configured in [None, Some(String::new()), Some("  ".to_string())] {
            let loc = classify(configured, &root(), &common());
            assert_eq!(
                loc,
                HooksLocation::GitDefault {
                    hooks_dir: PathBuf::from("/work/repo/.git/hooks")
                }
            );
            assert_eq!(
                loc.hook_file("post-checkout"),
                Some(PathBuf::from("/work/repo/.git/hooks/post-checkout"))
            );
            assert_eq!(
                loc.hook_file("post-merge"),
                Some(PathBuf::from("/work/repo/.git/hooks/post-merge"))
            );
        }
    }

    #[test]
    fn husky_runtime_dir_maps_to_user_managed_hook() {
        for configured in [".husky/_", ".husky/_/", "/work/repo/.husky/_"] {
            let loc = classify(Some(configured.to_string()), &root(), &common());
            assert_eq!(
                loc,
                HooksLocation::Husky {
                    hook_file: PathBuf::from("/work/repo/.husky/post-checkout")
                },
                "configured: {configured}"
            );
        }
    }

    #[test]
    fn husky_is_recognized_even_when_runtime_dir_is_not_generated_yet() {
        // No filesystem setup at all: classification must not depend on
        // `.husky/_` existing.
        let loc = classify(Some(".husky/_".to_string()), &root(), &common());
        assert!(matches!(loc, HooksLocation::Husky { .. }));
    }

    #[test]
    fn existing_custom_dir_resolves_relative_to_worktree_root() {
        let tmp = tempfile::TempDir::new().unwrap();
        let worktree = tmp.path();
        std::fs::create_dir_all(worktree.join("ci-hooks")).unwrap();

        let loc = classify(
            Some("ci-hooks".to_string()),
            worktree,
            &worktree.join(".git"),
        );

        assert_eq!(
            loc,
            HooksLocation::Custom {
                hooks_dir: worktree.join("ci-hooks")
            }
        );
    }

    #[test]
    fn absolute_existing_dir_is_custom() {
        let tmp = tempfile::TempDir::new().unwrap();
        let hooks = tmp.path().join("shared-hooks");
        std::fs::create_dir_all(&hooks).unwrap();

        let loc = classify(
            Some(hooks.to_string_lossy().into_owned()),
            &root(),
            &common(),
        );

        assert_eq!(loc, HooksLocation::Custom { hooks_dir: hooks });
    }

    #[test]
    fn nonexistent_dir_is_missing_and_uninstallable() {
        let tmp = tempfile::TempDir::new().unwrap();

        let loc = classify(
            Some("generated/hooks".to_string()),
            tmp.path(),
            &tmp.path().join(".git"),
        );

        assert_eq!(
            loc,
            HooksLocation::Missing {
                configured: "generated/hooks".to_string(),
                resolved: tmp.path().join("generated/hooks"),
            }
        );
        assert_eq!(loc.hook_file("post-checkout"), None);
    }

    #[test]
    fn husky_hook_file_derives_siblings() {
        let loc = classify(Some(".husky/_".to_string()), &root(), &common());
        assert_eq!(
            loc.hook_file("post-checkout"),
            Some(PathBuf::from("/work/repo/.husky/post-checkout"))
        );
        assert_eq!(
            loc.hook_file("post-merge"),
            Some(PathBuf::from("/work/repo/.husky/post-merge"))
        );
    }

    #[test]
    fn contains_portool_invocation_recognizes_every_form() {
        assert!(contains_portool_invocation(
            "#!/bin/sh\n# installed by portool\nexit 0\n"
        ));
        assert!(contains_portool_invocation(
            "#!/bin/sh\necho hi\n# >>> portool >>>\n...\n# <<< portool <<<\n"
        ));
        assert!(contains_portool_invocation(
            "#!/bin/sh\nif command -v portool >/dev/null 2>&1; then portool sync --quiet || true; fi\n"
        ));
        assert!(!contains_portool_invocation("#!/bin/sh\necho hi\n"));
    }

    #[test]
    fn shared_scope_is_uninstallable() {
        let loc = HooksLocation::SharedScope {
            configured: "/home/u/.githooks".to_string(),
            resolved: PathBuf::from("/home/u/.githooks"),
            scope: "global".to_string(),
        };
        assert_eq!(loc.hook_file("post-checkout"), None);
        assert_eq!(loc.hook_file("post-merge"), None);
    }

    #[test]
    fn relative_hooks_path_escaping_repo_is_outside() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path().join("repo");
        std::fs::create_dir_all(root.join(".git")).unwrap();
        std::fs::create_dir_all(tmp.path().join("shared-hooks")).unwrap();
        let root = root.canonicalize().unwrap();
        let resolved = root.join("../shared-hooks");
        assert!(!is_inside_repo(
            &lexical_normalize(&resolved),
            &root,
            &root.join(".git")
        ));
    }

    #[test]
    fn symlinked_hooks_dir_outside_repo_is_outside() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path().join("repo");
        std::fs::create_dir_all(&root).unwrap();
        std::fs::create_dir_all(tmp.path().join("real-hooks")).unwrap();
        std::os::unix::fs::symlink(tmp.path().join("real-hooks"), root.join("hooks-link")).unwrap();
        let root = root.canonicalize().unwrap();
        let resolved = root.join("hooks-link").canonicalize().unwrap();
        assert!(!is_inside_repo(&resolved, &root, &root.join(".git")));
    }

    #[test]
    fn hooks_dir_inside_repo_is_inside() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        std::fs::create_dir_all(root.join("ci-hooks")).unwrap();
        assert!(is_inside_repo(
            &root.join("ci-hooks"),
            &root,
            &root.join(".git")
        ));
    }
}
