//! Effective hooks-location discovery: where git will actually look for
//! `post-checkout` in this repository, honoring `core.hooksPath` (set by
//! hook managers like Husky) instead of assuming `<common_dir>/hooks`.

use crate::gitctx::{self, GitCtx};
use std::ffi::OsStr;
use std::path::{Component, Path, PathBuf};

/// The substring that marks a hook (or a line in one) as portool's own;
/// both `init` (idempotency) and `sync` (missing-hook hint) key off it.
pub const HOOK_MARKER: &str = "portool sync";

/// Where portool's `post-checkout` invocation belongs for this repository.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HooksLocation {
    /// No `core.hooksPath`: git's default `<common_dir>/hooks`.
    GitDefault { hooks_dir: PathBuf },
    /// `core.hooksPath` points at Husky's generated runtime dir
    /// (`.husky/_`). That dir is gitignored and regenerated by Husky, so
    /// portool's hook belongs in the user-managed `.husky/post-checkout`
    /// one level up, which Husky's own bootstrap dispatches to (keeping
    /// `HUSKY=0`, `~/.config/husky/init.sh`, PATH setup, `sh -e`, and
    /// exit-code propagation intact).
    Husky { hook_file: PathBuf },
    /// Some other `core.hooksPath` whose directory exists.
    Custom { hooks_dir: PathBuf },
    /// `core.hooksPath` is set but the directory doesn't exist (likely a
    /// generated dir portool doesn't recognize); installing anywhere would
    /// either be discarded or never run, so nothing is safe to touch.
    Missing {
        configured: String,
        resolved: PathBuf,
    },
}

impl HooksLocation {
    /// Resolves the effective hooks location for `ctx` by reading
    /// `core.hooksPath` (with `~` expanded) from the worktree.
    pub fn resolve(ctx: &GitCtx) -> HooksLocation {
        let configured = gitctx::config_path_value(&ctx.worktree_root, "core.hooksPath");
        classify(configured, &ctx.worktree_root, &ctx.common_dir)
    }

    /// The `post-checkout` file portool installs into (and `sync` checks),
    /// or `None` when no location is safe to auto-install into.
    pub fn post_checkout_file(&self) -> Option<PathBuf> {
        match self {
            HooksLocation::GitDefault { hooks_dir } | HooksLocation::Custom { hooks_dir } => {
                Some(hooks_dir.join("post-checkout"))
            }
            HooksLocation::Husky { hook_file } => Some(hook_file.clone()),
            HooksLocation::Missing { .. } => None,
        }
    }
}

/// Pure classification of a raw `core.hooksPath` value (spec: relative
/// paths resolve against the worktree root, per githooks(5) hooks running
/// at the top level of the working tree; an unset or empty value means
/// git's default directory).
fn classify(configured: Option<String>, worktree_root: &Path, common_dir: &Path) -> HooksLocation {
    let configured = match configured {
        Some(value) if !value.trim().is_empty() => value,
        _ => {
            return HooksLocation::GitDefault {
                hooks_dir: common_dir.join("hooks"),
            }
        }
    };

    let raw = PathBuf::from(&configured);
    let resolved = if raw.is_absolute() {
        raw
    } else {
        worktree_root.join(raw)
    };

    if is_husky_runtime_dir(&resolved) {
        // `.husky/_` -> the user-managed `.husky/post-checkout`. Husky is
        // recognized even before `_` is generated: the config pointing at
        // it is proof enough, and `.husky/` itself is a tracked dir.
        let husky_dir = resolved.parent().unwrap_or(&resolved).to_path_buf();
        return HooksLocation::Husky {
            hook_file: husky_dir.join("post-checkout"),
        };
    }

    if resolved.is_dir() {
        HooksLocation::Custom {
            hooks_dir: resolved,
        }
    } else {
        HooksLocation::Missing {
            configured,
            resolved,
        }
    }
}

/// True for any path whose final two components are `.husky/_` (Husky's
/// generated runtime dir), tolerating a trailing slash.
fn is_husky_runtime_dir(path: &Path) -> bool {
    let mut components = path.components().rev().filter_map(|c| match c {
        Component::Normal(name) => Some(name),
        _ => None,
    });
    components.next() == Some(OsStr::new("_")) && components.next() == Some(OsStr::new(".husky"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> PathBuf {
        PathBuf::from("/work/repo")
    }

    fn common() -> PathBuf {
        PathBuf::from("/work/repo/.git")
    }

    #[test]
    fn unset_and_empty_mean_git_default() {
        for configured in [None, Some(String::new()), Some("  ".to_string())] {
            let loc = classify(configured, &root(), &common());
            assert_eq!(
                loc,
                HooksLocation::GitDefault {
                    hooks_dir: PathBuf::from("/work/repo/.git/hooks")
                }
            );
            assert_eq!(
                loc.post_checkout_file(),
                Some(PathBuf::from("/work/repo/.git/hooks/post-checkout"))
            );
        }
    }

    #[test]
    fn husky_runtime_dir_maps_to_user_managed_hook() {
        for configured in [".husky/_", ".husky/_/", "/work/repo/.husky/_"] {
            let loc = classify(Some(configured.to_string()), &root(), &common());
            assert_eq!(
                loc,
                HooksLocation::Husky {
                    hook_file: PathBuf::from("/work/repo/.husky/post-checkout")
                },
                "configured: {configured}"
            );
        }
    }

    #[test]
    fn husky_is_recognized_even_when_runtime_dir_is_not_generated_yet() {
        // No filesystem setup at all: classification must not depend on
        // `.husky/_` existing.
        let loc = classify(Some(".husky/_".to_string()), &root(), &common());
        assert!(matches!(loc, HooksLocation::Husky { .. }));
    }

    #[test]
    fn existing_custom_dir_resolves_relative_to_worktree_root() {
        let tmp = tempfile::TempDir::new().unwrap();
        let worktree = tmp.path();
        std::fs::create_dir_all(worktree.join("ci-hooks")).unwrap();

        let loc = classify(
            Some("ci-hooks".to_string()),
            worktree,
            &worktree.join(".git"),
        );

        assert_eq!(
            loc,
            HooksLocation::Custom {
                hooks_dir: worktree.join("ci-hooks")
            }
        );
    }

    #[test]
    fn absolute_existing_dir_is_custom() {
        let tmp = tempfile::TempDir::new().unwrap();
        let hooks = tmp.path().join("shared-hooks");
        std::fs::create_dir_all(&hooks).unwrap();

        let loc = classify(
            Some(hooks.to_string_lossy().into_owned()),
            &root(),
            &common(),
        );

        assert_eq!(loc, HooksLocation::Custom { hooks_dir: hooks });
    }

    #[test]
    fn nonexistent_dir_is_missing_and_uninstallable() {
        let tmp = tempfile::TempDir::new().unwrap();

        let loc = classify(
            Some("generated/hooks".to_string()),
            tmp.path(),
            &tmp.path().join(".git"),
        );

        assert_eq!(
            loc,
            HooksLocation::Missing {
                configured: "generated/hooks".to_string(),
                resolved: tmp.path().join("generated/hooks"),
            }
        );
        assert_eq!(loc.post_checkout_file(), None);
    }
}
